name: tactician
channels:
  - conda-forge
  - defaults
dependencies:
  - bubblewrap
  - capnproto>=0.8,<1.0
  - compilers
  - opam
  - pkg-config
  - python=3.10
  - sysroot_linux-64=2.17
  - xxhash>=0.8
  - gmp
  - squashfuse
