name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1.2.3
        with:
          opam_file: 'coq-tactician-reinforce.opam.locked'
          coq_version: '8.11.2'
          ocaml_version: '4.11.2-flambda'
          install: |
            startGroup "Install dependencies"
            sudo apt update
            sudo apt-get --yes install graphviz capnproto libcapnp-dev pkg-config libev-dev
              export OPAMSOLVERTIMEOUT=120
              opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
              opam update -y
              opam install -y -j 2 -t ./coq-tactician-reinforce.opam.locked --deps-only
            endGroup
          script: |
            startGroup "Build"
              opam install -y -v -j 2 -t ./coq-tactician-reinforce.opam.locked
              opam list
            endGroup
            startGroup "Test"
              sudo chown coq:coq . # Ugly hack
              ./tests/external-tests.sh
            endGroup
