name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-11]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.12.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_ALL: >
            curl -O https://capnproto.org/capnproto-c++-0.10.3.tar.gz &&
            tar zxf capnproto-c++-0.10.3.tar.gz &&
            cd capnproto-c++-0.10.3 &&
            ./configure &&
            make -j6 check &&
            make install

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
